sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.3
script: bundle exec jekyll build --config _config.yml,_local.yml

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
