title:                跬步
tagline:              On Coding
description:          'Read | Think | Write'

url:                  http://hanjianwei.com
baseurl:              '/'
paginate:             5
permalink:            pretty
relative_permalinks:  true
cdn:                  http://xblog.qiniudn.com

github:
    repository_url:   https://github.com/hanjianwei/hanjianwei.github.io
    owner_name:       hanjianwei

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: "wechat"
    values:
      layout: page

exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, vendor]

lsi:      true
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - disable_indented_code_blocks
    - autolink
    - strikethrough
    - space_after_headers
    - superscript
    - underline
    - highlight
    - quote
    - footnotes

sass:
  style: :compressed

gems:
  - jemoji
  - jekyll-feed
