title:                跬步
tagline:              On Coding
description:          'Read | Think | Write'

url:                  http://hanjianwei.com
baseurl:              '/'
paginate:             5
permalink:            pretty
cdn:                  http://xblog.qiniudn.com

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

exclude: [LICENSE.md, Gemfile, Gemfile.lock, README.md, vendor]

lsi:      true
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - disable_indented_code_blocks
    - autolink
    - strikethrough
    - space_after_headers
    - superscript
    - underline
    - highlight
    - quote
    - footnotes

sass:
  style: :compressed

repository: hanjianwei/hanjianwei.github.io

gems:
  - jekyll-feed
  - jekyll-github-metadata
