url: http://hjw.xxx
ipynb_site: http://ooii.co
title: 跬步
author: Jianwei Han
email: hanjianwei@gmail.com

pygments: true
markdown: redcarpet
permalink: pretty
paginate: 10

redcarpet:
  extensions: [no_intra_emphasis, tables, fenced_code_blocks, autolink, strikethrough, space_after_headers, superscript]

exclude: [Rakefile]
