# Dependencies
markdown: redcarpet
pygments: true
redcarpet:
  extensions:
      - no_intra_emphasis
      - tables
      - fenced_code_blocks
      - disable_indented_code_blocks
      - autolink, strikethrough
      - space_after_headers
      - superscript

# Permalinks
permalink: pretty

# Setup
title: 跬步
tagline: 'On Coding'
description: 'My notes and thoughts.'
url: http://hjw.xxx

author:
    name: Jianwei Han
    email: hanjianwei@gmail.com

paginate: 5

exclude: [Rakefile]
