title: 跬步
description: 'My notes and thoughts.'
url: http://hanjianwei.com

paginate: 5
permalink: pretty

exclude: [Rakefile, Gemfile, Gemfile.lock]

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jemoji

links:
  - name: RSS
    url: /feed.xml
