title: 跬步
description: 'My notes and thoughts.'
url: http://hanjianwei.com

paginate: 5
permalink: pretty

exclude: [Rakefile, Gemfile, Gemfile.lock, README.md]

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - disable_indented_code_blocks
    - autolink
    - strikethrough
    - space_after_headers
    - superscript

sass:
  style: :compressed

gems:
  - jemoji

links:
  - name: RSS
    url: /feed.xml
