name:                 M-x
tagline:              butterfly
description:          Amazing physics going on...

url:                  http://hanjianwei.com
paginate:             5
permalink:            pretty

disqus:               hjwblog
cdn:                  http://xblog.qiniudn.com

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

exclude: [LICENSE.md, Gemfile, Gemfile.lock, README.md, vendor]

sass:
  style: :nested

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
