title:                M-x
tagline:              butterfly
description:          'Read | Think | Write'

url:                  http://hanjianwei.com
baseurl:              '/'
paginate:             5
permalink:            pretty
cdn:                  http://xblog.qiniudn.com

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

exclude: [LICENSE.md, Gemfile, Gemfile.lock, README.md, vendor]

lsi:      true

sass:
  style: :compressed

repository: hanjianwei/hanjianwei.github.io

gems:
  - jekyll-feed
  - jekyll-github-metadata
