# Setup
title: 跬步
description: 'My notes and thoughts.'
url: http://hjw.xxx

paginate: 5
permalink: pretty

exclude: [Rakefile]

sass:
  sass_dir: _sass
  style: :compressed

links:
  - name: RSS
    url: /feed.xml  
