title:          跬步
tagline:        On Coding
description:    'My notes and thoughts.'

url:            http://hanjianwei.com
baseurl:        '/'
paginate:       5
permalink:      date

defaults:
  -
    scope:
      path: ""
      type: post
    values:
      layout: post

exclude: [Rakefile, Gemfile, Gemfile.lock, README.md]

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - disable_indented_code_blocks
    - autolink
    - strikethrough
    - space_after_headers
    - superscript
    - underline
    - highlight
    - quote
    - footnotes

sass:
  style: :compressed

gems:
  - jemoji
