project:
  type: website

website:
  title: "Byte-Sized Blog"
  site-url: https://hanjianwei.com
  favicon: favicon.svg
  navbar:
    right:
      - icon: github
        href: https://github.com/hanjianwei
format:
  html:
    theme:
      - litera
    css: styles.css