baseURL = "https://hanjianwei.com/"
languageCode = "en-us"
title = "M-x butterfly"
theme = "lean"
disqusShortname = "hjwblog"
hasCJKLanguage = true
summaryLength = 128
paginate = 5

[author]
  name = "Jianwei Han"
  email = "blog@hanjianwei.com"

[social]
  github = "hanjianwei"
  twitter = "hanjianwei"

[params]
  since = "2013"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"

[permalinks]
  posts = "/:year/:month/:day/:filename/"

[markup]
  [markup.highlight]
    noClasses = false
