baseURL = "https://hanjianwei.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Stone Horse"
theme = "lean"
disqusShortname = "hjwblog"
hasCJKLanguage = true
summaryLength = 160
paginate = 5

[author]
  name = "Jianwei Han"
  email = "blog@hanjianwei.com"

[social]
  github = "hanjianwei"
  twitter = "hanjianwei"

[params]
  since = "2013"

[permalinks]
  posts = "/:year/:month/:day/:filename/"

[markup]
  [markup.highlight]
    noClasses = false
