baseURL = "https://hanjianwei.com/"
languageCode = "en-us"
title = "M-x butterfly"
theme = "blog"
disqusShortname = "hjwblog"
hasCJKLanguage = true
summaryLength = 128
Paginate = 5

[params]
  Since = "2013"
  Author = "Jianwei Han"
  GitHubUser = "hanjianwei"

[permalinks]
  posts = "/:year/:month/:day/:filename/"

[markup]
  [markup.highlight]
    noClasses = false